image: gradle:latest

variables:
  GOPTS: "--no-daemon --console=plain"
  CI: "true"
  BEFORE_TASK: ""
  AFTER_TASK: ""
  GCMD: "gradle"
  BUILD_TASK: "assemble"
  TEST_TASK: "check"

Compile:
  stage: build
  script: $GCMD $BEFORE_TASK $BUILD_TASK $AFTER_TASK $GOPTS

Test:
  stage: test
  script: $GCMD $BEFORE_TASK $TEST_TASK $AFTER_TASK $GOPTS
