image: gciatto/my-images:jdk11-gradlew5

variables:
  GOPTS: "--no-daemon --console=plain"

before_script:
  - chmod +x gradlew

cache:
  paths:
     - /root/.gradle/
     - gradle/
     - build/
     - .gradle/wrapper
     - .gradle/caches

build:
  stage: build
  script: ./gradlew assemble $GOPTS

test:
  stage: test
  script: ./gradlew check $GOPTS

deploy_artifacts:
  stage: deploy
  script:
    - ./gradlew bintrayUpload
  environment:
    name: Bintray
    url: https://bintray.com/gciatto-unibo/pika-lab
  when: on_success
  only:
    - /main/
