image: java:openjdk-8-alpine

variables:
  GOPTS: "--no-daemon --console=plain"

before_script:
  - chmod +x gradlew

cache:
  paths:
     - /root/.gradle/
     - gradle/
     - build/
     - .gradle/wrapper
     - .gradle/caches

build:
  stage: build
  script: ./gradlew assemble $GOPTS

test:
  stage: test
  script: ./gradlew check $GOPTS

