image: pikalab/ci:jdk12oracle-gradle6-git

variables:
  GOPTS: "--no-daemon --console=plain --stacktrace"
  CI: "true"
  BEFORE_TASK: ""
  AFTER_TASK: ""
  GCMD: "gradle"
  BUILD_TASK: "assemble"
  TEST_TASK: "check"
  BINTRAY_TASK: "publishAllToBintray"

before_script:
  - chmod +x gradlew

cache:
  paths:
    - /root/.gradle/
    - gradle/
    - build/
    - .gradle/

Compile:
  stage: build
  script: $GCMD $BEFORE_TASK $BUILD_TASK $AFTER_TASK $GOPTS

Test:
  stage: test
  script: $GCMD $BEFORE_TASK $TEST_TASK $AFTER_TASK $GOPTS

Automatically publish to Bintray (dev):
  stage: deploy
  script: $GCMD $BEFORE_TASK $BINTRAY_TASK $AFTER_TASK $GOPTS
  environment: &BintrayEnv
    name: Bintray
    url: "https://bintray.com/pika-lab/coordination"
  only:
    - /^develop$/

Automatically publish Releases to Bintray:
  stage: deploy
  script: $GCMD $BEFORE_TASK $BINTRAY_TASK $AFTER_TASK $GOPTS
  environment: *BintrayEnv
  only:
    - /^(master)|(release)$/

Manually publish to Bintray:
  stage: deploy
  script: $GCMD $BEFORE_TASK $BINTRAY_TASK $AFTER_TASK $GOPTS
  environment: *BintrayEnv
  when: manual
