rootProject.name = "coordination"

include("linda-core")
include("linda-logic")
include("tusow")
include("utils")
include("prologx")
include("test-utils")
include("linda-text")
include("linda-test")
include("presentation")
include("linda-core-presentation")
include("linda-logic-presentation")
include("linda-text-presentation")
include("linda-remote-client")
include("linda-logic-client")
include("linda-text-client")
include("tusow-cli")

include("control")
include("agency")